DROP TABLE IF EXISTS make;
CREATE TABLE make (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(32) DEFAULT NOT NULL
);

DROP TABLE IF EXISTS model;
CREATE TABLE model (
	id LONG AUTO_INCREMENT PRIMARY KEY,
	make_id INT DEFAULT NOT NULL,
	name VARCHAR(64) DEFAULT NULL,
	FOREIGN KEY (make_id) REFERENCES make(id)
);
