DROP TABLE IF EXISTS make;
CREATE TABLE make (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(32) DEFAULT NOT NULL
);

DROP TABLE IF EXISTS model;
CREATE TABLE model (
	id LONG AUTO_INCREMENT PRIMARY KEY,
	make_id INT DEFAULT NOT NULL,
	name VARCHAR(64) DEFAULT NULL,
	FOREIGN KEY (make_id) REFERENCES make(id)
);

DROP TABLE IF EXISTS listing;
CREATE TABLE listing (
	id LONG AUTO_INCREMENT PRIMARY KEY,
	make_id INT DEFAULT NOT NULL,
	model_id LONG DEFAULT NOT NULL,
	price DECIMAL DEFAULT 0,
	list_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (make_id) REFERENCES make(id),
	FOREIGN KEY (model_id) REFERENCES model(id)
);