DROP TABLE IF EXISTS manufacturer;
CREATE TABLE make (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(32) DEFAULT NOT NULL
);

INSERT INTO make(id,name) VALUES
	(1,'Acura'),
	(2,'Alfa Romeo'),
	(3,'Aston Martin'),
	(4,'Audi'),
	(5,'BMW'),
	(6,'Bently'),
	(7,'Buick'),
	(8,'Cadillac'),
	(9,'Chevrolet'),
	(10,'Chrysler'),
	(11,'Daewoo'),
	(12,'Daihatsu'),
	(13,'Dodge'),
	(14,'Eagle'),
	(15,'Ferrari'),
	(16,'Fiat'),
	(17,'Fisker'),
	(18,'Ford'),
	(19,'Freightliner'),
	(20,'GMC'),
	(21,'Genesis'),
	(22,'Geo'),
	(23,'Honda'),
	(24,'Hummer'),
	(25,'Hyundai'),
	(26,'Infiniti'),
	(27,'Isuzu'),
	(28,'Jaguar'),
	(29,'Jeep'),
	(30,'Kia'),
	(31,'Lamborghini'),
	(32,'Land Rover'),
	(33,'Lexus'),
	(34,'Lincoln'),
	(35,'Lotus'),
	(36,'Mazda'),
	(37,'Maserati'),
	(38,'Maybach'),
	(39,'Mclaren'),
	(40,'Mercedes-Benz'),
	(41,'Mercury'),
	(42,'Mini'),
	(43,'Mitsubishi'),
	(44,'Nissan'),
	(45,'Oldsmobile'),
	(46,'Panoz'),
	(47,'Plymouth'),
	(48,'Pontiac'),
	(49,'Porsche'),
	(50,'Ram'),
	(51,'Rolls-Royce'),
	(52,'Saab'),
	(53,'Saturn'),
	(54,'Smart'),
	(55,'Subaru'),
	(56,'Susuki'),
	(57,'Telsa'),
	(58,'Toyota'),
	(59,'Volkswagen'),
	(60,'Volvo');
